import { useEffect, useState } from 'react'
import { recommendationsApi, Recommendation } from '../api/client'
import Card from '../components/Card'
import Badge from '../components/Badge'
import Btn from '../components/Btn'
import Spinner from '../components/Spinner'

function priorityColor(p: string) { return p === 'HIGH' || p === 'CRITICAL' ? '#C0392B' : p === 'MEDIUM' ? '#C77700' : '#1F8A5A' }
function priorityBg(p: string) { return p === 'HIGH' || p === 'CRITICAL' ? '#FEE2E2' : p === 'MEDIUM' ? '#FBF0DD' : '#E7F3EC' }
function statusColor(s: string) { return s === 'APPROVED' ? '#1F8A5A' : s === 'DISMISSED' ? '#9AA3AD' : '#C77700' }
function statusBg(s: string) { return s === 'APPROVED' ? '#E7F3EC' : s === 'DISMISSED' ? '#EEF0F3' : '#FBF0DD' }

export default function Recommendations() {
  const [recs, setRecs] = useState<Recommendation[]>([])
  const [expanded, setExpanded] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [acting, setActing] = useState<string | null>(null)

  useEffect(() => {
    recommendationsApi.getAll().then(r => setRecs(r.data)).finally(() => setLoading(false))
  }, [])

  const respond = async (id: string, response: 'APPROVED' | 'DISMISSED' | 'REMIND_LATER') => {
    setActing(id)
    try {
      const res = await recommendationsApi.respond(id, response)
      setRecs(rs => rs.map(r => r.recommendationId === id ? res.data : r))
    } catch {} finally { setActing(null) }
  }

  if (loading) return <Spinner />

  const pending = recs.filter(r => r.response === 'PENDING' || r.response === 'REMIND_LATER').length
  const approved = recs.filter(r => r.response === 'APPROVED').length
  const dismissed = recs.filter(r => r.response === 'DISMISSED').length

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <div style={{ fontSize: 20, fontWeight: 700, color: '#14181F' }}>Recommendations</div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 12 }}>
        {[{ label: 'Pending', count: pending, color: '#C77700' }, { label: 'Approved', count: approved, color: '#1F8A5A' }, { label: 'Dismissed', count: dismissed, color: '#9AA3AD' }].map(({ label, count, color }) => (
          <Card key={label} style={{ textAlign: 'center', padding: '1rem' }}>
            <div style={{ fontSize: 28, fontWeight: 800, color }}>{count}</div>
            <div style={{ fontSize: 12, color: '#9AA3AD' }}>{label}</div>
          </Card>
        ))}
      </div>

      {recs.map(rec => (
        <Card key={rec.recommendationId} style={{ border: expanded === rec.recommendationId ? '2px solid #1A6EBD' : '1px solid #E2E8F0' }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', cursor: 'pointer' }}
            onClick={() => setExpanded(expanded === rec.recommendationId ? null : rec.recommendationId)}>
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                <Badge label={rec.priority} color={priorityColor(rec.priority)} bg={priorityBg(rec.priority)} />
                <Badge label={rec.response} color={statusColor(rec.response)} bg={statusBg(rec.response)} />
                <span style={{ fontSize: 11, color: '#9AA3AD' }}>{rec.agent}</span>
              </div>
              <div style={{ fontSize: 15, fontWeight: 700, color: '#14181F' }}>{rec.recommendationText}</div>
              <div style={{ fontSize: 12, color: '#64748B', marginTop: 4 }}>{rec.reason}</div>
            </div>
            <div style={{ textAlign: 'right', marginLeft: 16, flexShrink: 0 }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: '#1F8A5A' }}>{Math.round(rec.confidence * 100)}% confidence</div>
              <div style={{ fontSize: 18, color: '#9AA3AD', marginTop: 4 }}>{expanded === rec.recommendationId ? '▲' : '▼'}</div>
            </div>
          </div>

          {expanded === rec.recommendationId && (
            <div style={{ marginTop: 16, borderTop: '1px solid #E2E8F0', paddingTop: 16 }}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
                <div>
                  <div style={{ fontSize: 11, fontWeight: 700, color: '#9AA3AD', marginBottom: 8, textTransform: 'uppercase' }}>Expected Impact</div>
                  <div style={{ background: '#E7F3EC', borderRadius: 8, padding: '10px 12px', fontSize: 13, color: '#1F8A5A' }}>✓ {rec.expectedImpact}</div>
                </div>
                <div>
                  <div style={{ fontSize: 11, fontWeight: 700, color: '#9AA3AD', marginBottom: 8, textTransform: 'uppercase' }}>Generated By</div>
                  <div style={{ background: '#F8FAFC', borderRadius: 8, padding: '10px 12px', fontSize: 13, color: '#475569' }}>{rec.agent}</div>
                </div>
              </div>
              {(rec.response === 'PENDING' || rec.response === 'REMIND_LATER') && (
                <div style={{ display: 'flex', gap: 10 }}>
                  <Btn label="✓ Approve" variant="success" onClick={() => respond(rec.recommendationId, 'APPROVED')} disabled={acting === rec.recommendationId} />
                  <Btn label="Remind Later" variant="ghost" onClick={() => respond(rec.recommendationId, 'REMIND_LATER')} />
                  <Btn label="Dismiss" variant="danger" onClick={() => respond(rec.recommendationId, 'DISMISSED')} disabled={acting === rec.recommendationId} />
                </div>
              )}
              {rec.response === 'APPROVED' && (
                <div style={{ background: '#E7F3EC', borderRadius: 8, padding: '10px 14px', fontSize: 13, color: '#1F8A5A', fontWeight: 600 }}>✅ Approved · Digital Twin updating</div>
              )}
            </div>
          )}
        </Card>
      ))}
    </div>
  )
}
